# Generated by Django 3.0.6 on 2020-05-15 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null='true')),
                ('create_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
